micronaut:
  application:
    name: keyManagerGrpc
datasources:
  default:
    url: 'jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/pixservice'
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 'Adm!n1str@d0r'
    dialect: MYSQL

jpa.default.properties.hibernate.hbm2ddl.auto: update
jpa.default.properties.hibernate.show_swl: true
jpa.default.properties.hibernate.format_sql: true
