micronaut:
  application:
    name: keyManagerGrpc
datasources:
  default:
    url: 'jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/pixservice?useTimezone=true&serverTimezone=UTC'
    driverClassName: com.mysql.cj.jdbc.Driver
    username: '${MYSQL_USERNAME:root}'
    password: '${MYSQL_PASSWORD:Adm!n1str@d0r}'
    dialect: MYSQL

jpa.default.properties.hibernate.hbm2ddl.auto: update
jpa.default.properties.hibernate.show_swl: true
jpa.default.properties.hibernate.format_sql: true

sistemaExternos:
  contasItau: 'http://${ITAU_HOST:localhost}:${ITAU_PORT:9091}/api/v1/clientes'
  bcb: 'http://${BCB_HOST:localhost}:${BCB_PORT:8082}/api/v1/pix/keys'