micronaut:
  application:
    name: keyManagerGrpc
datasources:
  default:
    url: ${DB_URI:`jdbc:postgresql://localhost:5432/postgres`}
    driverClassName: org.postgresql.Driver
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:admin}
    schema-generate: CREATE_DROP
    dialect: ${DB_DIALECT:POSTGRES}
jpa:
  default:
    properties:
      hibernate.hbm2ddl.auto: 'create-drop'
      hibernate.show_sql: true

jpa.default.properties.hibernate.hbm2ddl.auto: update
jpa.default.properties.hibernate.show_swl: true
jpa.default.properties.hibernate.format_sql: true

sistemaExternos:
  contasItau: ${ITAU_URL:`http://localhost:9091/api/v1/clientes`}
  bcb: ${BCB_URL:`http://localhost:8082/api/v1/pix/keys`}